import { Dimensions, StyleSheet } from 'react-native';

import {
  TRAINING_BORDER,
  TRAINING_GREEN,
  TRAINING_MUTED,
  TRAINING_TEAL,
  TRAINING_TRACK,
} from '@/components/trainingsAndCourses/trainingData';
import { c, NU } from '@/utils/newUiCompact';

export const styles = StyleSheet.create({
  stateWrap: {
    minHeight: Math.max(Dimensions.get('window').height * 0.62, 360),
    justifyContent: 'center',
    alignItems: 'center',
    gap: c(12, 10),
    paddingHorizontal: c(12, 10),
  },
  pendingWrap: {
    minHeight: Math.max(Dimensions.get('window').height * 0.62, 360),
    justifyContent: 'center',
    paddingHorizontal: c(4, 2),
  },
  pendingCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#f0d9a8',
    borderRadius: NU.cardRadius,
    paddingVertical: c(22, 18),
    paddingHorizontal: c(18, 14),
    gap: c(12, 10),
    alignItems: 'center',
  },
  pendingBadge: {
    backgroundColor: '#fff6e8',
    borderWidth: 1,
    borderColor: '#f0d9a8',
    borderRadius: 99,
    paddingHorizontal: c(12, 10),
    paddingVertical: c(6, 5),
  },
  pendingBadgeText: {
    fontSize: c(11, 10),
    fontWeight: '800',
    letterSpacing: 0.5,
    textTransform: 'uppercase',
    color: '#8a6a2b',
  },
  pendingTitle: {
    fontSize: c(18, 16),
    fontWeight: '800',
    color: TRAINING_TEAL,
    textAlign: 'center',
    letterSpacing: -0.2,
  },
  pendingBody: {
    fontSize: c(14, 13),
    lineHeight: c(21, 19),
    color: TRAINING_MUTED,
    textAlign: 'center',
    fontWeight: '500',
  },
  pendingCheckBtn: {
    marginTop: c(4, 2),
    minWidth: c(160, 140),
    minHeight: c(48, 44),
    paddingHorizontal: c(20, 16),
    borderRadius: c(14, 12),
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  pendingCheckBtnBusy: {
    opacity: 0.85,
  },
  pendingCheckBtnText: {
    fontSize: c(14, 13),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  pendingHint: {
    fontSize: c(12, 11),
    lineHeight: c(17, 15),
    color: TRAINING_MUTED,
    textAlign: 'center',
    fontWeight: '500',
  },
  stateText: {
    fontSize: c(13.5, 12.5),
    color: TRAINING_MUTED,
    textAlign: 'center',
    lineHeight: c(20, 18),
    paddingHorizontal: c(12, 10),
  },
  retryText: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  keyboardPausedBar: {
    backgroundColor: '#0b1f18',
    paddingHorizontal: c(14, 12),
    paddingVertical: c(10, 8),
  },
  keyboardPausedText: {
    color: 'rgba(255,255,255,0.9)',
    fontSize: c(12, 11),
    fontWeight: '700',
  },
  heroBanner: {
    height: c(160, 140),
    borderRadius: NU.cardRadius,
    overflow: 'hidden',
    backgroundColor: '#d7e8db',
    position: 'relative',
  },
  heroBannerImage: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    width: '100%',
    height: '100%',
  },
  heroBannerInitials: {
    fontSize: c(26, 22),
    lineHeight: c(30, 26),
  },
  heroBannerScrim: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(8, 28, 18, 0.42)',
  },
  heroBannerTop: {
    position: 'absolute',
    top: c(12, 10),
    left: c(12, 10),
    right: c(12, 10),
    zIndex: 2,
    flexDirection: 'row',
    alignItems: 'center',
  },
  heroModePill: {
    paddingVertical: c(4, 3),
    paddingHorizontal: c(8, 6),
    borderRadius: c(5, 4),
    backgroundColor: '#e6f4e8',
  },
  heroModePillText: {
    fontSize: NU.label,
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  heroBannerCopy: {
    position: 'absolute',
    left: c(14, 12),
    right: c(14, 12),
    bottom: c(14, 12),
    gap: c(4, 3),
  },
  heroBannerEyebrow: {
    fontSize: c(11, 10),
    fontWeight: '700',
    letterSpacing: 0.8,
    textTransform: 'uppercase',
    color: 'rgba(255,255,255,0.8)',
  },
  heroBannerTitle: {
    fontSize: c(18, 16),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  heroBannerMeta: {
    fontSize: c(12.5, 11.5),
    color: 'rgba(255,255,255,0.88)',
  },
  heroCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: TRAINING_BORDER,
    borderRadius: NU.cardRadius,
    padding: c(15, 12),
    gap: c(8, 6),
  },
  certificateCard: {
    backgroundColor: '#e6f4e8',
    borderWidth: 1,
    borderColor: '#c8e0cc',
    borderRadius: NU.cardRadius,
    padding: c(15, 12),
    gap: c(6, 5),
  },
  certificateEyebrow: {
    fontSize: c(11, 10),
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: TRAINING_GREEN,
  },
  certificateTitle: {
    fontSize: NU.body,
    fontWeight: '800',
    color: '#14352a',
  },
  certificateMeta: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
    marginBottom: c(4, 2),
  },
  certificateBtn: {
    marginTop: c(4, 2),
    height: c(44, 40),
    borderRadius: 99,
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  certificateBtnBusy: {
    opacity: 0.75,
  },
  certificateBtnText: {
    fontSize: NU.body,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  tracker: { gap: c(8, 6) },
  trackerRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    gap: c(8, 6),
  },
  trackerLabel: {
    flex: 1,
    fontSize: c(13.5, 12.5),
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  trackerPercent: {
    fontSize: c(18, 16),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  track: {
    height: c(10, 8),
    borderRadius: 99,
    backgroundColor: TRAINING_TRACK,
    overflow: 'hidden',
  },
  fill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: TRAINING_GREEN,
  },
  progressSub: {
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
  },
  nextBanner: {
    backgroundColor: '#e6f4e8',
    borderRadius: NU.cardRadiusSm,
    padding: c(12, 10),
    gap: c(4, 3),
  },
  nextBannerLabel: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: TRAINING_GREEN,
  },
  nextBannerText: {
    fontSize: c(14, 13),
    fontWeight: '700',
    color: TRAINING_TEAL,
    lineHeight: c(20, 18),
  },
  howtoCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: TRAINING_BORDER,
    borderRadius: NU.cardRadius,
    padding: c(15, 12),
    gap: c(6, 4),
  },
  howtoTitle: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  howtoText: {
    fontSize: c(13, 12),
    color: TRAINING_MUTED,
    lineHeight: c(20, 18),
  },
  curriculumLabel: {
    alignSelf: 'flex-start',
    fontSize: c(12, 11),
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#FFFFFF',
    backgroundColor: TRAINING_GREEN,
    paddingHorizontal: c(10, 8),
    paddingVertical: c(5, 4),
    borderRadius: c(8, 7),
    overflow: 'hidden',
  },
  curriculumHelp: {
    fontSize: c(13, 12),
    lineHeight: c(18, 16),
    fontWeight: '700',
    color: '#1f6b36',
    backgroundColor: '#c8ebd2',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(7, 6),
    borderRadius: c(8, 7),
    overflow: 'hidden',
  },
  curriculumPanel: {
    gap: c(8, 6),
    padding: c(12, 10),
    borderRadius: NU.cardRadius,
    backgroundColor: '#e8f6ec',
    borderWidth: 1,
    borderColor: '#b9dfc2',
  },
  curriculumCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#9ed0aa',
    borderRadius: NU.cardRadius,
    overflow: 'hidden',
  },
  notesSection: {
    gap: c(8, 6),
  },
  notesLabel: {
    marginTop: c(4, 2),
    fontSize: NU.body,
    fontWeight: '700',
    letterSpacing: 1.2,
    textTransform: 'uppercase',
    color: TRAINING_MUTED,
  },
  notesHelp: {
    marginTop: -c(8, 6),
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
    lineHeight: c(17, 15),
  },
  notesCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: TRAINING_BORDER,
    borderRadius: NU.cardRadius,
    overflow: 'hidden',
  },
  notesRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(10, 8),
    paddingVertical: c(12, 10),
    paddingHorizontal: c(12, 10),
  },
  notesRowBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: TRAINING_TRACK,
  },
  notesIconWrap: {
    width: c(28, 26),
    height: c(28, 26),
    borderRadius: c(7, 6),
    backgroundColor: '#fdecea',
    alignItems: 'center',
    justifyContent: 'center',
  },
  notesCopy: {
    flex: 1,
    minWidth: 0,
    gap: 1,
  },
  notesTitle: {
    fontSize: c(13.5, 12.5),
    fontWeight: '600',
    color: TRAINING_TEAL,
  },
  notesMeta: {
    fontSize: c(11, 10),
    color: TRAINING_MUTED,
    fontWeight: '500',
  },
  notesActions: {
    alignItems: 'flex-end',
    gap: c(6, 5),
  },
  notesActionText: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  notesDownloadText: {
    color: TRAINING_TEAL,
  },
  notesActionTextDisabled: {
    opacity: 0.45,
  },
  notesOpen: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  curriculumSectionBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#c5e3cd',
  },
  curriculumSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(10, 8),
    paddingVertical: c(13, 11),
    paddingHorizontal: c(12, 10),
    backgroundColor: '#f2faf4',
  },
  curriculumSectionHeaderOpen: {
    paddingBottom: c(10, 8),
    backgroundColor: '#d9f0df',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#a8d4b4',
  },
  curriculumSectionBadge: {
    width: c(30, 28),
    height: c(30, 28),
    borderRadius: c(15, 14),
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  curriculumSectionBadgeDone: {
    backgroundColor: '#1f6b36',
  },
  curriculumSectionBadgeText: {
    fontSize: c(12, 11),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  curriculumSectionBadgeTextDone: {
    color: '#FFFFFF',
  },
  curriculumSectionCopy: {
    flex: 1,
    minWidth: 0,
    gap: c(2, 1),
  },
  curriculumSectionTitle: {
    fontSize: c(14.5, 13.5),
    fontWeight: '800',
    color: TRAINING_TEAL,
    lineHeight: c(19, 17),
  },
  curriculumSectionMeta: {
    fontSize: c(11.5, 10.5),
    color: '#4a7a58',
  },
  curriculumProgressPill: {
    fontSize: c(11, 10),
    fontWeight: '800',
    color: '#1f6b36',
    backgroundColor: '#c8ebd2',
    paddingHorizontal: c(7, 6),
    paddingVertical: c(3, 2),
    borderRadius: c(6, 5),
    overflow: 'hidden',
  },
  curriculumLessonList: {
    paddingTop: c(8, 6),
    paddingBottom: c(10, 8),
    paddingHorizontal: c(10, 8),
    backgroundColor: '#dff3e5',
    gap: c(8, 6),
  },
  curriculumLessonNest: {
    marginLeft: c(14, 12),
    paddingLeft: c(10, 8),
    borderLeftWidth: 3,
    borderLeftColor: TRAINING_GREEN,
    gap: c(5, 4),
  },
  curriculumEmptyText: {
    fontSize: c(12, 11),
    color: '#4a7a58',
    paddingVertical: c(8, 6),
    paddingHorizontal: c(4, 2),
  },
  curriculumLessonWrap: {
    gap: c(5, 4),
  },
  curriculumLessonItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    paddingVertical: c(6, 5),
    paddingHorizontal: c(8, 7),
    borderRadius: c(8, 7),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#b9dfc2',
  },
  curriculumLessonLocked: {
    opacity: 0.88,
    backgroundColor: '#f4faf6',
  },
  curriculumLessonExpired: {
    opacity: 0.85,
    backgroundColor: '#f7f9f8',
    borderColor: '#dce4df',
  },
  curriculumTypeIconWrapExpired: {
    backgroundColor: '#eef2f0',
  },
  curriculumLessonOpen: {
    borderColor: TRAINING_GREEN,
    backgroundColor: '#e4f5ea',
  },
  curriculumLessonActive: {
    borderColor: '#1f6b36',
    backgroundColor: '#d2edd9',
  },
  curriculumLessonDone: {
    backgroundColor: '#f0faf3',
    borderColor: '#a8d4b4',
  },
  stickyDemoWrap: {
    backgroundColor: '#FFFFFF',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: TRAINING_BORDER,
  },
  stickyDemoToolbar: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    paddingHorizontal: c(14, 12),
    paddingBottom: c(10, 8),
  },
  stickyDemoNav: {
    paddingHorizontal: c(10, 8),
    paddingVertical: c(7, 6),
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#eef3f0',
  },
  stickyDemoNavText: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  stickyDemoClose: {
    marginLeft: 'auto',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(7, 6),
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#14352a',
  },
  stickyDemoCloseText: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: '#FFFFFF',
  },
  toolDisabled: {
    opacity: 0.4,
  },
  curriculumTypeIconWrap: {
    width: c(22, 20),
    height: c(22, 20),
    borderRadius: c(6, 5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  curriculumLessonCopy: {
    flex: 1,
    minWidth: 0,
    gap: 0,
  },
  downloadIconBtn: {
    width: c(26, 24),
    height: c(26, 24),
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#eef3f0',
  },
  downloadCluster: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(4, 3),
  },
  downloadIconBtnDone: {
    backgroundColor: '#e6f4e8',
    borderWidth: 1,
    borderColor: '#c8e0cc',
  },
  downloadedLabel: {
    fontSize: c(9.5, 9),
    fontWeight: '800',
    color: TRAINING_GREEN,
    letterSpacing: 0.2,
  },
  curriculumLessonTitle: {
    fontSize: c(12.5, 11.5),
    lineHeight: c(16, 15),
    fontWeight: '600',
    color: TRAINING_TEAL,
    flexShrink: 1,
  },
  curriculumLessonTitleDone: {
    color: TRAINING_MUTED,
  },
  curriculumLessonTitleExpired: {
    color: '#4a6354',
  },
  curriculumLessonMeta: {
    fontSize: c(10.5, 9.5),
    color: TRAINING_MUTED,
    fontWeight: '500',
  },
  curriculumLessonMetaExpired: {
    color: TRAINING_MUTED,
  },
  statusDone: {
    width: c(18, 16),
    height: c(18, 16),
    borderRadius: 99,
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  statusOpen: {
    width: c(18, 16),
    height: c(18, 16),
    borderRadius: 99,
    borderWidth: 1.5,
    borderColor: '#c5d4c8',
    backgroundColor: '#FFFFFF',
  },
  statusOpenDisabled: {
    borderColor: '#cfd6d1',
    backgroundColor: '#eef1ef',
  },
  dayStatus: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    color: TRAINING_MUTED,
  },
  dayStatusExam: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    color: '#8352c0',
  },
  dayStatusDone: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  lessonMeta: {
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
  },
  inlinePlayer: {
    paddingHorizontal: c(14, 12),
    paddingBottom: c(14, 12),
    gap: c(8, 6),
  },
  apiVideoView: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#000000',
  },
  apiVideoLoading: {
    width: '100%',
    aspectRatio: 16 / 9,
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#14352a',
    alignItems: 'center',
    justifyContent: 'center',
    gap: c(8, 6),
  },
  lessonBodyText: {
    fontSize: c(13, 12),
    lineHeight: c(20, 18),
    color: TRAINING_TEAL,
  },
  videoStage: {
    height: c(168, 148),
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#14352a',
    alignItems: 'center',
    justifyContent: 'center',
    gap: c(10, 8),
    paddingHorizontal: c(16, 12),
    overflow: 'hidden',
    position: 'relative',
  },
  videoStageImage: {
    ...StyleSheet.absoluteFill,
  },
  videoStageScrim: {
    ...StyleSheet.absoluteFill,
    backgroundColor: 'rgba(8, 28, 18, 0.45)',
  },
  playOuter: {
    width: c(56, 50),
    height: c(56, 50),
    borderRadius: 99,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1,
  },
  playInner: {
    width: c(40, 36),
    height: c(40, 36),
    borderRadius: 99,
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  videoCaption: {
    fontSize: c(12.5, 11.5),
    color: 'rgba(255,255,255,0.92)',
    textAlign: 'center',
    zIndex: 1,
  },
  watchMetaRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  watchMeta: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: TRAINING_MUTED,
  },
  watchTrack: {
    height: c(8, 7),
    borderRadius: 99,
    backgroundColor: TRAINING_TRACK,
    overflow: 'hidden',
  },
  watchFill: {
    height: '100%',
    borderRadius: 99,
    backgroundColor: TRAINING_GREEN,
  },
  inlineHint: {
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
    lineHeight: c(17, 15),
  },
  inlineLive: {
    paddingHorizontal: c(14, 12),
    paddingBottom: c(14, 12),
    gap: c(8, 6),
  },
  liveJoinCard: {
    width: '100%',
    borderWidth: 1,
    borderColor: '#c5dde8',
    backgroundColor: '#f3fafc',
    borderRadius: NU.cardRadiusSm,
    padding: c(14, 12),
    gap: c(6, 5),
  },
  liveJoinCardAttended: {
    borderColor: '#c8e0cc',
    backgroundColor: '#e6f4e8',
  },
  attendedBanner: {
    fontSize: c(13, 12),
    fontWeight: '700',
    color: TRAINING_GREEN,
    lineHeight: c(18, 16),
  },
  fieldRow: {
    gap: c(2, 1),
  },
  fieldLabel: {
    fontSize: c(11, 10),
    fontWeight: '700',
    color: TRAINING_MUTED,
    letterSpacing: 0.3,
  },
  fieldValue: {
    minHeight: c(18, 16),
    fontSize: c(13, 12),
    color: TRAINING_TEAL,
    lineHeight: c(18, 16),
    flexShrink: 1,
  },
  fieldValueLink: {
    textDecorationLine: 'underline',
    fontWeight: '700',
  },
  liveJoinEyebrow: {
    fontSize: c(11, 10),
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: TRAINING_TEAL,
  },
  liveJoinTitle: {
    fontSize: NU.body,
    fontWeight: '800',
    color: '#14352a',
    flexShrink: 1,
  },
  inlineVenue: {
    paddingHorizontal: c(14, 12),
    paddingBottom: c(14, 12),
    gap: c(8, 6),
    alignItems: 'center',
  },
  venueName: {
    fontSize: NU.body,
    fontWeight: '800',
    color: TRAINING_TEAL,
    textAlign: 'center',
  },
  passCodeRow: {
    width: '100%',
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: c(10, 8),
    paddingHorizontal: c(12, 10),
    paddingVertical: c(10, 8),
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#eef3f0',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: TRAINING_BORDER,
  },
  passCode: {
    flex: 1,
    minWidth: 0,
    fontSize: c(13, 12),
    fontWeight: '700',
    letterSpacing: 0.3,
    color: TRAINING_TEAL,
    flexWrap: 'wrap',
  },
  passCodeCopyBtn: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: c(4, 3),
    minHeight: c(36, 32),
    paddingHorizontal: c(10, 8),
    borderRadius: 999,
    backgroundColor: '#FFFFFF',
    borderWidth: StyleSheet.hairlineWidth,
    borderColor: TRAINING_BORDER,
    flexShrink: 0,
  },
  passCodeCopyBtnDone: {
    backgroundColor: TRAINING_GREEN,
    borderColor: TRAINING_GREEN,
  },
  passCodeCopyLabel: {
    fontSize: c(11, 10),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  passCodeCopyLabelDone: {
    color: '#FFFFFF',
  },
  venueQrBlock: {
    width: '100%',
    alignItems: 'center',
    gap: c(8, 6),
    paddingVertical: c(6, 4),
  },
  qrSectionLabel: {
    fontSize: c(12, 11),
    fontWeight: '700',
    color: TRAINING_MUTED,
    textAlign: 'center',
  },
  qrOuter: {
    padding: c(10, 8),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: TRAINING_BORDER,
    borderRadius: NU.cardRadiusSm,
  },
  qrApiImage: {
    width: c(168, 148),
    height: c(168, 148),
  },
  qrInner: {
    gap: 1,
  },
  qrRow: {
    flexDirection: 'row',
    gap: 1,
  },
  qrCell: {
    width: c(8, 7),
    height: c(8, 7),
  },
  qrCellOn: {
    backgroundColor: '#10281f',
  },
  qrCellOff: {
    backgroundColor: '#FFFFFF',
  },
  liveThumb: {
    height: c(100, 88),
    borderRadius: NU.cardRadiusSm,
    width: '100%',
  },
  liveUrl: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  primaryBtn: {
    height: c(46, 42),
    borderRadius: 99,
    backgroundColor: TRAINING_TEAL,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'stretch',
  },
  primaryBtnText: {
    fontSize: NU.body,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
