export type EnterpriseApiResponse = {
  id: string;
  business_short_name: string;
  business_legal_name: string;
  business_description: string | null;
  business_email: string | null;
  business_phone: string | null;
  registered_address: string | null;
  business_address: string | null;
  communication_address: string | null;
  suite_unit?: string | null;
  logo_url: string | null;
  business_images: string | null;
  registration_number?: string | null;
  business_category?: string | null;
  website_url?: string | null;
  year_founded?: number | null;
  primary_contact_name?: string | null;
  primary_contact_title?: string | null;
  secondary_email?: string | null;
  secondary_phone?: string | null;
  brand_color?: string | null;
  tagline?: string | null;
  status: boolean;
  created_at?: string | null;
  category: string | null;
  status_label: string | null;
  members_count: number | null;
  revenue: number | null;
  joined_date?: string | null;
  rating?: number | null;
};

export type EnterpriseListItem = {
  id: string;
  name: string;
  description: string;
  category: string;
  location: string;
  members: number;
  revenue: number;
  joined: string;
  status: string;
  isVerified: boolean;
  products: number;
  rating: string;
  heroImage: string;
  businessEmail: string | null;
  businessPhone: string | null;
};
