import { StyleSheet } from 'react-native';

import {
  FEATURED_BANNER_HEIGHT,
  FEATURED_BANNER_WIDTH,
  HOME_ACCENT_GREEN,
  HOME_CATEGORY_ICON_SIZE,
  HOME_CATEGORY_ITEM_WIDTH,
  HOME_ENTERPRISE_AVATAR_SIZE,
  HOME_H_PAD,
  HOME_HEADER_ARC_LEFT_SIZE,
  HOME_HEADER_ARC_RIGHT_SIZE,
  HOME_HEADER_BADGE_RADIUS,
  HOME_HEADER_BADGE_SIZE,
  HOME_HEADER_ICON_RADIUS,
  HOME_HEADER_ICON_SIZE,
  HOME_PRIMARY,
  HOME_STAT_CARD_WIDTH,
  HOME_STAT_GAP,
  HOME_TEXT_BLACK,
  HOME_TEXT_MUTED,
  HOME_WHITE,
} from '@/components/home/homeData';
import { isSmallDevice } from '@/utils/responsive';
import { shadowSm } from '@/utils/shadows';

export const homePartsStyles = StyleSheet.create({
  statsRow: {
    flexDirection: 'row',
    paddingHorizontal: HOME_H_PAD,
    gap: HOME_STAT_GAP,
    marginTop: isSmallDevice ? -40 : -48,
    marginBottom: isSmallDevice ? 16 : 20,
  },
  categoriesRow: {
    gap: isSmallDevice ? 10 : 14,
    paddingBottom: 4,
    marginBottom: isSmallDevice ? 16 : 20,
  },
  enterprisesList: {
    gap: isSmallDevice ? 8 : 10,
    marginBottom: 8,
  },
  enterprisesLoading: {
    paddingVertical: 4,
    alignItems: 'stretch',
  },
  enterprisesEmpty: {
    paddingVertical: 24,
    alignItems: 'center',
  },
  enterprisesEmptyText: {
    fontSize: 13,
    color: HOME_TEXT_MUTED,
  },
  headerArcLeft: {
    position: 'absolute',
    top: -HOME_H_PAD - HOME_HEADER_ARC_LEFT_SIZE *-0.36,
    left: -HOME_H_PAD - HOME_HEADER_ARC_LEFT_SIZE * 0.2,
    width: HOME_HEADER_ARC_LEFT_SIZE,
    height: HOME_HEADER_ARC_LEFT_SIZE,
    borderRadius: HOME_HEADER_ARC_LEFT_SIZE / 2,
    backgroundColor: 'rgba(255,255,255,0.07)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.1)',
  },
  headerArcRight: {
    position: 'absolute',
    top: -HOME_H_PAD - HOME_HEADER_ARC_RIGHT_SIZE * 0.4,
    right: -HOME_H_PAD - HOME_HEADER_ARC_RIGHT_SIZE * 0.48,
    width: HOME_HEADER_ARC_RIGHT_SIZE,
    height: HOME_HEADER_ARC_RIGHT_SIZE,
    borderRadius: HOME_HEADER_ARC_RIGHT_SIZE / 2,
    backgroundColor: 'rgba(255,255,255,0.05)',
  },
  headerIconWrap: {
    width: HOME_HEADER_ICON_SIZE,
    height: HOME_HEADER_ICON_SIZE,
    borderRadius: HOME_HEADER_ICON_RADIUS,
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.3)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  bellOuter: {
    width: HOME_HEADER_ICON_SIZE,
    height: HOME_HEADER_ICON_SIZE,
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerIconBadge: {
    position: 'absolute',
    top: isSmallDevice ? 4 : 6,
    right: isSmallDevice ? 2 : 4,
    minWidth: HOME_HEADER_BADGE_SIZE,
    height: HOME_HEADER_BADGE_SIZE,
    borderRadius: HOME_HEADER_BADGE_RADIUS,
    backgroundColor: HOME_ACCENT_GREEN,
    borderWidth: 2,
    borderColor: HOME_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 4,
    transform: [
      { translateX: HOME_HEADER_BADGE_RADIUS },
      { translateY: -HOME_HEADER_BADGE_RADIUS },
    ],
  },
  headerIconBadgeText: {
    fontSize: isSmallDevice ? 9 : 10,
    fontWeight: '700',
    color: HOME_WHITE,
    lineHeight: HOME_HEADER_BADGE_SIZE - 4,
    textAlign: 'center',
  },
  searchBar: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255,255,255,0.15)',
    borderRadius: isSmallDevice ? 14 : 16,
    paddingHorizontal: isSmallDevice ? 12 : 14,
    paddingVertical: isSmallDevice ? 10 : 13,
    gap: isSmallDevice ? 8 : 10,
    borderWidth: 1,
    borderColor: 'rgba(255,255,255,0.12)',
  },
  searchPlaceholder: {
    flex: 1,
    fontSize: isSmallDevice ? 13 : 14,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.55)',
  },
  quickStatCard: {
    width: HOME_STAT_CARD_WIDTH,
    backgroundColor: HOME_WHITE,
    borderRadius: isSmallDevice ? 16 : 20,
    paddingVertical: isSmallDevice ? 10 : 12,
    paddingHorizontal: isSmallDevice ? 4 : 6,
    alignItems: 'center',
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.04)',
    ...shadowSm,
  },
  quickStatIcon: {
    width: isSmallDevice ? 24 : 28,
    height: isSmallDevice ? 24 : 28,
    borderRadius: isSmallDevice ? 8 : 10,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: isSmallDevice ? 6 : 8,
  },
  quickStatValue: {
    fontSize: isSmallDevice ? 16 : 20,
    lineHeight: isSmallDevice ? 20 : 24,
    fontWeight: '800',
    color: HOME_TEXT_BLACK,
    letterSpacing: -0.5,
    marginBottom: 2,
  },
  quickStatLabel: {
    fontSize: isSmallDevice ? 9 : 10,
    lineHeight: isSmallDevice ? 12 : 13,
    fontWeight: '500',
    color: HOME_TEXT_MUTED,
    textAlign: 'center',
  },
  sectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: isSmallDevice ? 8 : 10,
  },
  sectionTitle: {
    fontSize: isSmallDevice ? 15 : 17,
    lineHeight: isSmallDevice ? 20 : 24,
    fontWeight: '800',
    color: HOME_TEXT_BLACK,
    letterSpacing: -0.3,
  },
  sectionAction: {
    fontSize: isSmallDevice ? 12 : 13,
    lineHeight: isSmallDevice ? 18 : 20,
    fontWeight: '600',
    color: HOME_PRIMARY,
  },
  categoryItem: {
    alignItems: 'center',
    width: HOME_CATEGORY_ITEM_WIDTH,
  },
  categoryIcon: {
    width: HOME_CATEGORY_ICON_SIZE,
    height: HOME_CATEGORY_ICON_SIZE,
    borderRadius: isSmallDevice ? 16 : 20,
    backgroundColor: HOME_WHITE,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: isSmallDevice ? 6 : 8,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    ...shadowSm,
  },
  categoryIconActive: {
    backgroundColor: HOME_PRIMARY,
    borderColor: HOME_PRIMARY,
    shadowOpacity: 0,
    elevation: 0,
  },
  categoryEmoji: {
    fontSize: isSmallDevice ? 20 : 24,
  },
  categoryEmojiActive: {
    opacity: 1,
  },
  categoryLabel: {
    fontSize: isSmallDevice ? 10 : 11,
    lineHeight: isSmallDevice ? 13 : 14,
    fontWeight: '500',
    color: HOME_TEXT_MUTED,
    textAlign: 'center',
  },
  categoryLabelActive: {
    fontWeight: '700',
    color: HOME_PRIMARY,
  },
  featuredBanner: {
    borderRadius: isSmallDevice ? 16 : 20,
    overflow: 'hidden',
    height: FEATURED_BANNER_HEIGHT,
    marginBottom: isSmallDevice ? 18 : 24,
    position: 'relative',
    ...shadowSm,
  },
  featuredImage: {
    width: FEATURED_BANNER_WIDTH,
    height: FEATURED_BANNER_HEIGHT,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  featuredOverlayWrap: {
    position: 'absolute',
    top: 0,
    left: 0,
    width: FEATURED_BANNER_WIDTH,
    height: FEATURED_BANNER_HEIGHT,
  },
  featuredContent: {
    position: 'absolute',
    left: 0,
    top: 0,
    bottom: 0,
    paddingHorizontal: isSmallDevice ? 14 : 18,
    paddingVertical: isSmallDevice ? 12 : 16,
    justifyContent: 'center',
    maxWidth: '68%',
  },
  featuredTag: {
    fontSize: isSmallDevice ? 9 : 10,
    fontWeight: '700',
    color: HOME_ACCENT_GREEN,
    letterSpacing: 0.08 * 10,
    textTransform: 'uppercase',
  },
  featuredTitle: {
    fontSize: isSmallDevice ? 14 : 16,
    fontWeight: '800',
    color: HOME_WHITE,
    marginTop: isSmallDevice ? 2 : 4,
    letterSpacing: -0.3,
  },
  featuredMeta: {
    fontSize: isSmallDevice ? 10 : 11,
    fontWeight: '500',
    color: 'rgba(255,255,255,0.7)',
    marginTop: 2,
  },
  featuredJoinBtn: {
    position: 'absolute',
    right: isSmallDevice ? 10 : 14,
    top: '50%',
    transform: [{ translateY: isSmallDevice ? -14 : -16 }],
    paddingHorizontal: isSmallDevice ? 12 : 14,
    paddingVertical: isSmallDevice ? 6 : 8,
    backgroundColor: HOME_WHITE,
    borderRadius: isSmallDevice ? 10 : 12,
  },
  featuredJoinText: {
    fontSize: isSmallDevice ? 10 : 11,
    fontWeight: '700',
    color: HOME_PRIMARY,
  },
  enterpriseCard: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: HOME_WHITE,
    borderRadius: isSmallDevice ? 14 : 18,
    padding: isSmallDevice ? 10 : 14,
    gap: isSmallDevice ? 10 : 12,
    borderWidth: 1,
    borderColor: 'rgba(0,0,0,0.05)',
    ...shadowSm,
  },
  enterpriseAvatar: {
    width: HOME_ENTERPRISE_AVATAR_SIZE,
    height: HOME_ENTERPRISE_AVATAR_SIZE,
    borderRadius: isSmallDevice ? 12 : 14,
    backgroundColor: HOME_PRIMARY,
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  enterpriseAvatarImage: {
    width: '100%',
    height: '100%',
  },
  enterpriseAvatarText: {
    fontSize: isSmallDevice ? 18 : 20,
    fontWeight: '700',
    color: HOME_WHITE,
  },
  enterpriseMain: {
    flex: 1,
    minWidth: 0,
  },
  enterpriseNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 5,
    marginBottom: 2,
  },
  enterpriseName: {
    flexShrink: 1,
    fontSize: isSmallDevice ? 13 : 14,
    lineHeight: isSmallDevice ? 18 : 20,
    fontWeight: '700',
    color: HOME_TEXT_BLACK,
  },
  enterpriseMeta: {
    fontSize: isSmallDevice ? 10 : 11,
    lineHeight: isSmallDevice ? 14 : 15,
    fontWeight: '500',
    color: HOME_TEXT_MUTED,
    marginBottom: isSmallDevice ? 2 : 4,
  },
  enterpriseRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 6,
  },
  starsRow: {
    flexDirection: 'row',
    gap: 1,
  },
  enterpriseRatingText: {
    fontSize: isSmallDevice ? 10 : 11,
    lineHeight: isSmallDevice ? 13 : 14,
    fontWeight: '500',
    color: HOME_TEXT_MUTED,
  },
  pressed: {
    opacity: 0.92,
    transform: [{ scale: 0.98 }],
  },

});
