import { Dimensions, StyleSheet } from 'react-native';

import {
  TRAINING_BORDER,
  TRAINING_GREEN,
  TRAINING_MUTED,
  TRAINING_TEAL,
  TRAINING_TRACK,
} from '@/components/trainingsAndCourses/trainingData';
import { c, NU } from '@/utils/newUiCompact';

export const styles = StyleSheet.create({
  stateWrapCentered: {
    minHeight: Dimensions.get('window').height * 0.55,
    alignItems: 'center',
    justifyContent: 'center',
    gap: c(12, 10),
    paddingHorizontal: NU.hPad,
  },
  stateText: {
    fontSize: NU.body,
    color: TRAINING_MUTED,
    textAlign: 'center',
  },
  retryBtn: {
    paddingHorizontal: c(14, 12),
    paddingVertical: c(8, 7),
    borderRadius: 99,
    backgroundColor: TRAINING_TEAL,
  },
  retryText: {
    fontSize: NU.body,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  media: {
    height: c(200, 170),
    position: 'relative',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  mediaImage: {
    ...StyleSheet.absoluteFill,
  },
  mediaInitials: {
    fontSize: c(28, 24),
    lineHeight: c(32, 28),
  },
  body: {
    paddingHorizontal: NU.hPad,
    paddingTop: NU.bodyPadTop,
    paddingBottom: NU.bodyPadBottom,
    gap: c(18, 14),
  },
  titleBlock: {
    gap: c(8, 6),
  },
  pendingBanner: {
    backgroundColor: '#fff6e8',
    borderWidth: 1,
    borderColor: '#f0d9a8',
    borderRadius: NU.cardRadius,
    paddingVertical: c(12, 10),
    paddingHorizontal: c(12, 10),
    gap: c(4, 3),
  },
  pendingBannerEyebrow: {
    fontSize: c(11, 10),
    fontWeight: '800',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: '#8a6a2b',
  },
  pendingBannerText: {
    fontSize: c(13, 12),
    lineHeight: c(18, 16),
    fontWeight: '600',
    color: TRAINING_TEAL,
  },
  kindRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    flexWrap: 'wrap',
  },
  badge: {
    fontSize: c(10, 9),
    fontWeight: '800',
    paddingHorizontal: c(8, 7),
    paddingVertical: c(3, 2),
    borderRadius: 99,
    overflow: 'hidden',
  },
  kindMeta: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
  },
  title: {
    fontSize: NU.heading,
    fontWeight: '800',
    color: TRAINING_TEAL,
    letterSpacing: -0.4,
  },
  titleFlex: {
    flex: 1,
  },
  titlePriceRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: c(12, 10),
  },
  priceCol: {
    alignItems: 'flex-end',
    gap: c(2, 1),
  },
  seatsUrgencyBadge: {
    marginTop: c(4, 3),
    fontSize: c(11.5, 10.5),
    fontWeight: '800',
    letterSpacing: 0.2,
  },
  seatsUrgencyLow: {
    color: '#c2410c',
  },
  seatsUrgencyFilled: {
    color: '#b91c1c',
  },
  priceWas: {
    fontSize: c(12.5, 11.5),
    fontWeight: '600',
    color: TRAINING_MUTED,
    textDecorationLine: 'line-through',
  },
  couponChip: {
    alignSelf: 'flex-start',
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    backgroundColor: '#e6f4e8',
    borderWidth: 1,
    borderColor: '#b7dfc0',
    borderRadius: 999,
    paddingHorizontal: c(10, 8),
    paddingVertical: c(4, 3),
  },
  couponChipPressed: {
    opacity: 0.85,
  },
  couponChipCopied: {
    backgroundColor: TRAINING_GREEN,
    borderColor: TRAINING_GREEN,
  },
  couponChipText: {
    fontSize: c(12, 11),
    fontWeight: '800',
    letterSpacing: 0.3,
    color: TRAINING_GREEN,
  },
  couponChipTextCopied: {
    color: '#FFFFFF',
  },
  programSubtitle: {
    fontSize: NU.subtitle,
    lineHeight: c(20, 18),
    fontWeight: '600',
    color: TRAINING_MUTED,
  },
  priceInline: {
    fontSize: NU.heading,
    fontWeight: '800',
    color: TRAINING_GREEN,
    letterSpacing: -0.3,
    marginTop: c(2, 1),
  },
  ratingSummary: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
  },
  ratingScore: {
    fontSize: c(15, 14),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  ratingCount: {
    fontSize: c(13, 12),
    color: TRAINING_MUTED,
  },
  stars: {
    fontWeight: '800',
    color: TRAINING_GREEN,
    letterSpacing: 1,
  },
  starsEmpty: {
    color: '#c8e0cc',
  },
  description: {
    fontSize: NU.link,
    lineHeight: c(22, 20),
    color: '#3c6b47',
  },
  tagRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    alignItems: 'center',
    gap: c(8, 6),
  },
  tag: {
    backgroundColor: '#e6f4e8',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(5, 4),
    borderRadius: 99,
    alignItems: 'center',
    justifyContent: 'center',
  },
  tagText: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    color: TRAINING_GREEN,
    textAlign: 'center',
    includeFontPadding: false,
    textAlignVertical: 'center',
  },
  factRow: {
    flexDirection: 'row',
    gap: c(8, 6),
  },
  factChip: {
    flex: 1,
    backgroundColor: '#f4f8f5',
    borderWidth: 1,
    borderColor: '#e8f0ea',
    borderRadius: NU.cardRadiusSm,
    paddingVertical: c(12, 10),
    paddingHorizontal: c(10, 8),
    gap: c(4, 3),
  },
  factLabel: {
    fontSize: c(10.5, 9.5),
    fontWeight: '700',
    letterSpacing: 0.7,
    textTransform: 'uppercase',
    color: TRAINING_MUTED,
  },
  factValue: {
    fontSize: c(12.5, 11.5),
    fontWeight: '700',
    color: TRAINING_TEAL,
    lineHeight: c(17, 15),
  },
  glanceHint: {
    marginTop: c(8, 6),
    fontSize: c(12.5, 11.5),
    lineHeight: c(18, 16),
    color: TRAINING_MUTED,
  },
  chipRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: c(8, 6),
  },
  infoChip: {
    fontSize: c(12, 11),
    fontWeight: '600',
    color: TRAINING_TEAL,
    backgroundColor: TRAINING_TRACK,
    paddingHorizontal: c(10, 8),
    paddingVertical: c(6, 5),
    borderRadius: 99,
    overflow: 'hidden',
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: TRAINING_BORDER,
    borderRadius: NU.cardRadius,
    padding: c(15, 12),
    gap: c(10, 8),
  },
  ratingHero: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(14, 12),
    backgroundColor: '#e6f4e8',
    borderRadius: NU.cardRadius,
    paddingVertical: c(16, 13),
    paddingHorizontal: c(16, 13),
    borderWidth: 1,
    borderColor: '#c8e0cc',
  },
  ratingHeroScore: {
    fontSize: c(36, 30),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  ratingHeroCopy: {
    flex: 1,
    gap: c(4, 3),
  },
  ratingHeroMeta: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
  },
  reviewStack: {
    gap: c(10, 8),
  },
  discussCard: {
    backgroundColor: '#f3fafc',
    borderWidth: 1,
    borderColor: '#c5dde8',
    borderRadius: NU.cardRadius,
    padding: c(14, 12),
    gap: c(12, 10),
  },
  discussCardLocked: {
    backgroundColor: '#f7f8f9',
    borderColor: TRAINING_BORDER,
  },
  discussHero: {
    flexDirection: 'row',
    gap: c(10, 8),
    alignItems: 'center',
  },
  discussIconWrap: {
    width: c(40, 36),
    height: c(40, 36),
    borderRadius: c(20, 18),
    backgroundColor: '#e5f4f8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  discussIconText: {
    fontSize: c(15, 13),
    fontWeight: '800',
    color: TRAINING_TEAL,
  },
  discussHeroCopy: {
    flex: 1,
    gap: c(2, 1),
  },
  discussTitle: {
    fontSize: NU.body,
    fontWeight: '800',
    color: '#14352a',
  },
  discussSubtitle: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
    lineHeight: c(17, 15),
  },
  discussSample: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#d7e8ef',
    borderRadius: NU.cardRadiusSm,
    padding: c(12, 10),
    gap: c(6, 5),
  },
  discussSampleLabel: {
    fontSize: c(11, 10),
    fontWeight: '700',
    letterSpacing: 0.4,
    textTransform: 'uppercase',
    color: TRAINING_TEAL,
  },
  discussSampleQuestion: {
    fontSize: c(13.5, 12.5),
    fontWeight: '700',
    color: '#14352a',
    lineHeight: c(19, 17),
  },
  discussSampleReply: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
    lineHeight: c(18, 16),
  },
  discussComposerPreview: {
    borderWidth: 1,
    borderColor: '#c5dde8',
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#FFFFFF',
    paddingVertical: c(12, 10),
    paddingHorizontal: c(12, 10),
  },
  discussComposerPlaceholder: {
    fontSize: c(13, 12),
    color: TRAINING_MUTED,
  },
  discussHint: {
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
    lineHeight: c(17, 15),
  },
  discussLockedBox: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    backgroundColor: '#eef1f3',
    borderRadius: NU.cardRadiusSm,
    paddingVertical: c(12, 10),
    paddingHorizontal: c(12, 10),
  },
  discussLockedText: {
    flex: 1,
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
    lineHeight: c(18, 16),
  },
  reviewActions: {
    marginTop: c(4, 2),
    gap: c(10, 8),
  },
  addReviewBtn: {
    height: c(44, 40),
    borderRadius: 99,
    backgroundColor: TRAINING_TEAL,
    alignItems: 'center',
    justifyContent: 'center',
  },
  addReviewBtnText: {
    fontSize: NU.body,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  reviewCard: {
    backgroundColor: '#f7faf8',
    borderWidth: 1,
    borderColor: '#e8f0ea',
    borderRadius: NU.cardRadius,
    padding: c(14, 12),
    gap: c(10, 8),
  },
  reviewTop: {
    flexDirection: 'row',
    gap: c(10, 8),
  },
  reviewAvatar: {
    width: c(40, 36),
    height: c(40, 36),
    borderRadius: c(20, 18),
    backgroundColor: '#e6f4e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  reviewAvatarText: {
    fontSize: c(15, 13),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  reviewCopy: {
    flex: 1,
    gap: c(3, 2),
  },
  reviewNameRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    flexWrap: 'wrap',
  },
  verifiedPill: {
    fontSize: c(10.5, 9.5),
    fontWeight: '700',
    color: TRAINING_GREEN,
    backgroundColor: '#e6f4e8',
    paddingHorizontal: c(8, 6),
    paddingVertical: c(3, 2),
    borderRadius: 99,
    overflow: 'hidden',
  },
  reviewRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
  },
  reviewComment: {
    fontSize: NU.link,
    lineHeight: c(21, 19),
    color: TRAINING_TEAL,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: c(12, 10),
    paddingVertical: c(10, 8),
  },
  infoBorder: {
    borderBottomWidth: 1,
    borderBottomColor: TRAINING_TRACK,
  },
  checkpointRow: {
    paddingVertical: c(12, 10),
    gap: c(4, 3),
  },
  checkpointPill: {
    alignSelf: 'flex-start',
    fontSize: NU.label,
    fontWeight: '700',
    paddingVertical: c(3, 2),
    paddingHorizontal: c(7, 6),
    borderRadius: c(5, 4),
    overflow: 'hidden',
    marginBottom: c(2, 1),
  },
  checkpointExam: {
    color: '#8352c0',
    backgroundColor: '#f2e9fb',
  },
  checkpointMilestone: {
    color: TRAINING_GREEN,
    backgroundColor: '#e6f4e8',
  },
  infoCopy: {
    flex: 1,
    gap: c(3, 2),
  },
  infoTitle: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  infoMeta: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
  },
  linkText: {
    marginTop: c(2, 1),
    fontSize: c(12.5, 11.5),
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  section: {
    gap: c(10, 8),
  },
  sectionLabel: {
    fontSize: NU.body,
    fontWeight: '700',
    letterSpacing: 1.3,
    textTransform: 'uppercase',
    color: TRAINING_MUTED,
  },
  softStack: {
    gap: c(8, 6),
  },
  softTile: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: c(12, 10),
    backgroundColor: '#f4f8f5',
    borderWidth: 1,
    borderColor: '#e8f0ea',
    borderRadius: NU.cardRadius,
    paddingVertical: c(13, 11),
    paddingHorizontal: c(13, 11),
  },
  instructorCard: {
    backgroundColor: '#eef7f0',
    borderWidth: 1,
    borderColor: '#d7eadc',
    borderRadius: NU.cardRadius,
    padding: c(15, 12),
    gap: c(10, 8),
  },
  instructorName: {
    fontSize: NU.cardTitle,
    fontWeight: '800',
    color: TRAINING_TEAL,
  },
  proseBlock: {
    backgroundColor: '#f4f8f5',
    borderRadius: NU.cardRadius,
    borderWidth: 1,
    borderColor: '#e8f0ea',
    paddingVertical: c(14, 12),
    paddingHorizontal: c(14, 12),
    gap: c(8, 6),
  },
  proseText: {
    fontSize: NU.link,
    lineHeight: c(22, 20),
    color: TRAINING_TEAL,
    fontWeight: '500',
  },
  proseMuted: {
    fontSize: c(12.5, 11.5),
    lineHeight: c(18, 16),
    color: TRAINING_MUTED,
  },
  faqList: {
    gap: c(10, 8),
  },
  faqCard: {
    backgroundColor: '#f4f8f5',
    borderRadius: NU.cardRadius,
    borderWidth: 1,
    borderColor: '#e8f0ea',
    overflow: 'hidden',
  },
  faqCardOpen: {
    backgroundColor: '#eef7f0',
    borderColor: '#cfe3d4',
  },
  faqHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(10, 8),
    paddingVertical: c(13, 11),
    paddingHorizontal: c(12, 10),
  },
  faqHeaderPressed: {
    opacity: 0.88,
  },
  faqIndex: {
    width: c(34, 30),
    height: c(34, 30),
    borderRadius: NU.cardRadiusSm,
    backgroundColor: '#ffffff',
    borderWidth: 1,
    borderColor: '#dfeae2',
    alignItems: 'center',
    justifyContent: 'center',
  },
  faqIndexOpen: {
    backgroundColor: TRAINING_GREEN,
    borderColor: TRAINING_GREEN,
  },
  faqIndexText: {
    fontSize: c(11, 10),
    fontWeight: '800',
    color: TRAINING_MUTED,
    letterSpacing: 0.2,
  },
  faqIndexTextOpen: {
    color: '#ffffff',
  },
  faqQuestion: {
    flex: 1,
    fontSize: NU.link,
    lineHeight: c(20, 18),
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  faqQuestionOpen: {
    color: TRAINING_GREEN,
  },
  faqAnswerWrap: {
    marginHorizontal: c(12, 10),
    marginBottom: c(13, 11),
    paddingTop: c(10, 8),
    borderTopWidth: 1,
    borderTopColor: '#d7eadc',
  },
  faqAnswer: {
    fontSize: c(13, 12),
    lineHeight: c(20, 18),
    color: TRAINING_TEAL,
    fontWeight: '500',
  },
  learnList: {
    gap: c(8, 6),
  },
  learnRow: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    gap: c(10, 8),
    backgroundColor: '#f4f8f5',
    borderRadius: NU.cardRadiusSm,
    borderWidth: 1,
    borderColor: '#e8f0ea',
    paddingVertical: c(11, 9),
    paddingHorizontal: c(12, 10),
  },
  learnDot: {
    width: c(22, 20),
    height: c(22, 20),
    borderRadius: 99,
    backgroundColor: '#e6f4e8',
    alignItems: 'center',
    justifyContent: 'center',
    marginTop: c(1, 0),
  },
  learnDotText: {
    fontSize: c(11, 10),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  learnText: {
    flex: 1,
    fontSize: NU.link,
    lineHeight: c(20, 18),
    color: TRAINING_TEAL,
    fontWeight: '600',
  },
  notesList: {
    gap: c(8, 6),
  },
  noteTile: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(12, 10),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#d7eadc',
    borderRadius: NU.cardRadius,
    paddingVertical: c(12, 10),
    paddingHorizontal: c(12, 10),
  },
  noteTilePressed: {
    backgroundColor: '#f0f7f2',
    borderColor: TRAINING_GREEN,
  },
  noteIconWrap: {
    width: c(40, 36),
    height: c(40, 36),
    borderRadius: c(10, 8),
    backgroundColor: '#fde8e6',
    alignItems: 'center',
    justifyContent: 'center',
  },
  noteIconText: {
    fontSize: c(10, 9),
    fontWeight: '800',
    color: '#b42318',
    letterSpacing: 0.4,
  },
  noteCopy: {
    flex: 1,
    minWidth: 0,
    gap: c(2, 1),
  },
  noteTitle: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_TEAL,
    lineHeight: c(19, 17),
  },
  noteMeta: {
    fontSize: c(12, 11),
    color: TRAINING_MUTED,
    fontWeight: '500',
  },
  noteActions: {
    alignItems: 'flex-end',
    gap: c(6, 5),
  },
  noteOpenPill: {
    backgroundColor: '#e6f4e8',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(6, 5),
    borderRadius: 99,
  },
  noteDownloadPill: {
    backgroundColor: '#eef6f4',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(6, 5),
    borderRadius: 99,
  },
  noteOpenText: {
    fontSize: c(12, 11),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  noteDownloadText: {
    fontSize: c(12, 11),
    fontWeight: '800',
    color: TRAINING_TEAL,
  },
  noteActionDisabled: {
    opacity: 0.45,
  },
  notesEmpty: {
    backgroundColor: '#f4f8f5',
    borderRadius: NU.cardRadius,
    borderWidth: 1,
    borderColor: '#e8f0ea',
    borderStyle: 'dashed',
    paddingVertical: c(18, 14),
    paddingHorizontal: c(14, 12),
    alignItems: 'center',
  },
  notesEmptyText: {
    fontSize: c(13, 12),
    color: TRAINING_MUTED,
    fontWeight: '600',
  },
  bio: {
    marginTop: c(2, 1),
    fontSize: NU.link,
    lineHeight: c(21, 19),
    color: TRAINING_TEAL,
  },
  bullet: {
    fontSize: NU.link,
    lineHeight: c(21, 19),
    color: TRAINING_TEAL,
  },
  mutedLine: {
    fontSize: c(12.5, 11.5),
    color: TRAINING_MUTED,
  },
  sessionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(12, 10),
    paddingVertical: c(14, 12),
  },
  sessionRowExpanded: {
    paddingBottom: c(8, 6),
  },
  sessionBlockBorder: {
    borderBottomWidth: 1,
    borderBottomColor: TRAINING_TRACK,
  },
  sessionIndex: {
    width: c(34, 30),
    height: c(34, 30),
    borderRadius: c(17, 15),
    backgroundColor: '#e6f4e8',
    alignItems: 'center',
    justifyContent: 'center',
  },
  sessionIndexText: {
    fontSize: c(13, 12),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  sessionCopy: {
    flex: 1,
    gap: c(3, 2),
  },
  sessionTitle: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_TEAL,
  },
  sessionStatus: {
    fontSize: c(11.5, 10.5),
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
  curriculumLabel: {
    alignSelf: 'flex-start',
    fontSize: c(12, 11),
    fontWeight: '800',
    letterSpacing: 1.1,
    textTransform: 'uppercase',
    color: '#FFFFFF',
    backgroundColor: TRAINING_GREEN,
    paddingHorizontal: c(10, 8),
    paddingVertical: c(5, 4),
    borderRadius: c(8, 7),
    overflow: 'hidden',
  },
  curriculumHint: {
    fontSize: c(13, 12),
    lineHeight: c(18, 16),
    fontWeight: '700',
    color: '#1f6b36',
    backgroundColor: '#c8ebd2',
    paddingHorizontal: c(10, 8),
    paddingVertical: c(7, 6),
    borderRadius: c(8, 7),
    overflow: 'hidden',
  },
  curriculumPanel: {
    gap: c(8, 6),
    padding: c(12, 10),
    borderRadius: NU.cardRadius,
    backgroundColor: '#e8f6ec',
    borderWidth: 1,
    borderColor: '#b9dfc2',
  },
  curriculumCard: {
    backgroundColor: '#FFFFFF',
    borderWidth: 1.5,
    borderColor: '#9ed0aa',
    borderRadius: NU.cardRadius,
    overflow: 'hidden',
  },
  curriculumSectionBorder: {
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#c5e3cd',
  },
  curriculumSectionHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(10, 8),
    paddingVertical: c(13, 11),
    paddingHorizontal: c(12, 10),
    backgroundColor: '#f2faf4',
  },
  curriculumSectionHeaderOpen: {
    paddingBottom: c(10, 8),
    backgroundColor: '#d9f0df',
    borderBottomWidth: StyleSheet.hairlineWidth,
    borderBottomColor: '#a8d4b4',
  },
  curriculumSectionBadge: {
    width: c(30, 28),
    height: c(30, 28),
    borderRadius: c(15, 14),
    backgroundColor: TRAINING_GREEN,
    alignItems: 'center',
    justifyContent: 'center',
  },
  curriculumSectionBadgeText: {
    fontSize: c(12, 11),
    fontWeight: '800',
    color: '#FFFFFF',
  },
  curriculumSectionCopy: {
    flex: 1,
    minWidth: 0,
    gap: c(2, 1),
  },
  curriculumSectionTitle: {
    fontSize: c(14.5, 13.5),
    fontWeight: '800',
    color: TRAINING_TEAL,
    lineHeight: c(19, 17),
  },
  curriculumSectionMeta: {
    fontSize: c(11.5, 10.5),
    color: '#4a7a58',
  },
  curriculumProgressPill: {
    fontSize: c(11, 10),
    fontWeight: '800',
    color: '#1f6b36',
    backgroundColor: '#c8ebd2',
    paddingHorizontal: c(7, 6),
    paddingVertical: c(3, 2),
    borderRadius: c(6, 5),
    overflow: 'hidden',
  },
  curriculumLessonList: {
    paddingTop: c(8, 6),
    paddingBottom: c(10, 8),
    paddingHorizontal: c(10, 8),
    backgroundColor: '#dff3e5',
  },
  curriculumLessonNest: {
    marginLeft: c(14, 12),
    paddingLeft: c(10, 8),
    borderLeftWidth: 3,
    borderLeftColor: TRAINING_GREEN,
    gap: c(5, 4),
  },
  curriculumEmptyText: {
    fontSize: c(12, 11),
    color: '#4a7a58',
    paddingVertical: c(8, 6),
    paddingHorizontal: c(4, 2),
  },
  curriculumItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(8, 6),
    paddingVertical: c(6, 5),
    paddingHorizontal: c(8, 7),
    borderRadius: c(8, 7),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#b9dfc2',
  },
  curriculumItemLocked: {
    opacity: 0.88,
    backgroundColor: '#f4faf6',
  },
  curriculumTypeIconWrap: {
    width: c(22, 20),
    height: c(22, 20),
    borderRadius: c(6, 5),
    alignItems: 'center',
    justifyContent: 'center',
  },
  curriculumItemCopy: {
    flex: 1,
    minWidth: 0,
    gap: 0,
  },
  curriculumItemRight: {
    minWidth: c(22, 20),
    alignItems: 'center',
    justifyContent: 'center',
  },
  curriculumPreviewPill: {
    fontSize: c(9.5, 8.5),
    fontWeight: '800',
    color: TRAINING_GREEN,
    backgroundColor: '#e6f4e8',
    paddingHorizontal: c(6, 5),
    paddingVertical: c(2, 1),
    borderRadius: c(5, 4),
    overflow: 'hidden',
  },
  curriculumItemTitle: {
    fontSize: c(12.5, 11.5),
    lineHeight: c(16, 15),
    fontWeight: '600',
    color: TRAINING_TEAL,
  },
  curriculumItemMeta: {
    fontSize: c(10.5, 9.5),
    color: TRAINING_MUTED,
    fontWeight: '500',
  },
  conceptItem: {
    fontSize: c(13, 12),
    lineHeight: c(19, 17),
    color: TRAINING_TEAL,
  },
  infoIconWrap: {
    width: c(40, 36),
    height: c(40, 36),
    borderRadius: c(12, 10),
    alignItems: 'center',
    justifyContent: 'center',
  },
  infoEyebrow: {
    fontSize: c(10.5, 9.5),
    fontWeight: '700',
    letterSpacing: 0.6,
    textTransform: 'uppercase',
    color: TRAINING_MUTED,
  },
  instructorRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: c(12, 10),
  },
  instructorAvatar: {
    width: c(52, 46),
    height: c(52, 46),
    borderRadius: c(26, 23),
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#d7eadc',
    alignItems: 'center',
    justifyContent: 'center',
    overflow: 'hidden',
  },
  instructorAvatarImage: {
    width: '100%',
    height: '100%',
  },
  instructorAvatarText: {
    fontSize: c(17, 15),
    fontWeight: '800',
    color: TRAINING_GREEN,
  },
  instructorCopy: {
    flex: 1,
    gap: c(2, 1),
  },
  docsLabel: {
    marginTop: c(8, 6),
  },
  actionLink: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: c(8, 6),
  },
  actionLinkText: {
    fontSize: NU.link,
    fontWeight: '700',
    color: TRAINING_GREEN,
  },
});
